name: Build APK
on: 
  push:
    branches: [ main ]
  workflow_dispatch: # Энэ нь гараар ажиллуулах боломж олгоно

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet and Dependencies
        run: |
          pip install flet yt-dlp

      - name: Build APK
        run: |
          # Flet-ийн сүүлийн хувилбарт заавал хэрэгтэй тохиргоо
          flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
